---
- name: install fake s3
  gem:
    name: fakes3
    state: present
    user_install: no

- name: copy fake s3 systemd unit file into place
  template:
    src: fakes3.service.j2
    dest: /etc/systemd/system/fakes3.service

- name: ensure fake s3 is enabled
  systemd:
    daemon_reload: yes
    name: fakes3
    state: started
    enabled: yes

- name: check fakes3 is listening
  command: netstat -tulpn

- name: grep fakes3
  shell: systemctl | grep fakes3

- name: journalctl
  command: journalctl

- name: check fakes3 is running
  command: systemctl status fakes3

- name: install s3cmd
  apt:
    package: s3cmd
    state: present
